### ISSUE TITLE
[FEATURE REQUEST] - Compatibility with Freemoji

### ISSUE THREAD

**Issue by whitetxt** [An00nymushun/DiscordEmojiParty#2]
Currently, the plugin is incompatible with freemoji, it would be nice to see them work together, I don't know if thats possible though.

**Comment by whitetxt** [comment]
Plus its a little annoying to have to turn off freemoji and turn this on just to use it.

**Comment by An00nymushun** [comment]
Try the new version (1.2)

**Comment by whitetxt** [comment]
That works great, good job!
