### ISSUE TITLE
[BUG] - Cannot read property "length" of undefined

### ISSUE THREAD

**Issue by whitetxt** [An00nymushun/DiscordEmojiParty#3]
Just found this recently, it seems to happen when a url is used for an emoji (from Freemoji plugin)
![image](https://user-images.githubusercontent.com/54776821/144675559-f6dddc99-2c50-4a6c-a0a3-82aa4aaa227d.png)
If a global Discord emoji is used, or a server emoji is used, this does not happen.

**Comment by whitetxt** [comment]
Update: After a bit more testing, it seems to only happen when the emoji is copied and pasted after typing
![broek](https://user-images.githubusercontent.com/54776821/144676000-aae65454-e6ce-4cbb-96cb-fac915b2d398.gif)

**Comment by An00nymushun** [comment]
That's an issue with Freemoji at https://github.com/QbDesu/BetterDiscordAddons/blob/potato/Plugins/Freemoji/Freemoji.plugin.js#L298
Because the created message has no invalidEmojis field
